# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-12
    steps:
      - run: brew install lima
      - run: nerdctl.lima pull public.ecr.aws/docker/library/alpine:latest
      - run: nerdctl.lima images -a
