# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    strategy:
      matrix: 
        os: [macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - run: limactl start
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
