# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    strategy:
      matrix: 
        os: [macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: setup docker
        uses: docker-practice/actions-setup-docker@1.0.11
      - run: limactl start
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
