# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: ubuntu-latest
    steps:
      - run: brew install nerdctl
      - run: nerdctl pull public.ecr.aws/docker/library/alpine:latest
      - run: nerdctl images -a
