# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-11
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
